# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

# This template will build and test your projects
# * Caches downloaded dependencies and plugins between invocation.
# * Verify but don't deploy merge requests.
# * Deploy built artifacts from master branch only.

variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  # As of Maven 3.3.0 instead of this you MAY define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # As of Maven 3.6.1, the use of `--no-tranfer-progress` (or `-ntp`) suppresses download and upload messages. The use
  # of the `Slf4jMavenTransferListener` is no longer necessary.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
  #   -DinstallAtEnd=true
  #   -DdeployAtEnd=true

stages:
  - backend_install
  - frontend_package
  - git_inspector

image: tommasoagnola/ingsw1:1.0.2

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
# Be aware that `mvn deploy` will install the built jar into this repository. If you notice your cache size
# increasing, consider adding `-Dmaven.install.skip=true` to `MAVEN_OPTS` or in `.mvn/maven.config`
cache:
  paths:
    - .m2/repository

backend-install:
  stage: backend_install
  before_script:
    - cd tictactoe
    - cd backend
  script:
    - 'mvn $MAVEN_CLI_OPTS clean'
    - 'mvn $MAVEN_CLI_OPTS install'
    - cd ../..
  only:
    - main
    - dev
  artifacts:
    paths:
      - tictactoe/backend/target/*.jar

frontend-package:
  stage: frontend_package
  before_script:
    - cd tictactoe
    - cd frontend
  script:
    - 'mvn $MAVEN_CLI_OPTS clean'
#    - 'mvn install:install-file -Dfile=../backend/target/backend-1.0.0.jar -DgroupId=ch.supsi.localchat -DartifactId=backend -Dversion=1.0.0 -Dpackaging=jar'
    - 'mvn $MAVEN_CLI_OPTS package'
    - cd ../..
  only:
    - main
    - dev
  artifacts:
    paths:
      - tictactoe/frontend/target/*.jar

git-inspector:
  stage: git_inspector
  script:
    - env PYTHONIOENCODING=utf-8 gitinspector -x dependencies --weeks --grading --format=html > gitinspector.html
  only:
    - main
    - dev
  artifacts:
    paths:
      - gitinspector.html
